<?php
namespace App\Http\Channels;

use Illuminate\Notifications\Channels\DatabaseChannel as IlluminateDatabaseChannel;
use Illuminate\Notifications\Notification;

class DatabaseChannel extends IlluminateDatabaseChannel
{
    protected function buildPayload($notifiable, Notification $notification): array
    {
        $data = $this->getData($notifiable, $notification);
//
        return [
            'id' => $notification->id,
            'type' => $notification::class,
            'data' => $data,
            'read_at'  => null,
            // Customize any columns
        ];
        return [];
    }

    public function send($notifiable, Notification $notification)
    {
//        return [];
        return parent::send($notifiable, $notification); // TODO: Change the autogenerated stub
    }
}
